server_name: 'isatidis.com'

mysql: 'mysql+mysqldb://plankroot:wratho544648@192.168.0.108/isatis?charset=utf8'

celery:
    backend: 'redis://pe123123letmeknowit@192.168.0.108:6379/15'
    broker: 'amqp://isatis:wratho544648@192.168.0.108:5672//'